---
- name: Installation of curl
  apt:
      pkg: curl
      state: present
      update_cache: true

- name: Check if Netdata is installed
  stat:
      path: /etc/netdata
  register: netdata

- name: Cloning Netdata installation script
  get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /home/arsciand/
        mode: 0755
  when: netdata

- name: Executing kickstart.sh (Netdata installation script)
  command: sh kickstart.sh --dont-wait
  args:
      chdir: /home/arsciand/
  register: output
  when: netdata

- debug:
      var: output
