---
- name: Installation of curl
  apt:
      pkg: curl
      state: present
      update_cache: true

- name: Check if Netdata is installed
  stat:
      path: /etc/netdata
  register: netdata

- name: Runing Netdata installaion script
  command: curl https://my-netdata.io/kickstart.sh > kickstart.sh && sh kickstart.sh --dont-wait
  args:
      warn: false
  when: netdata
  register: output

- debug:
      var: output
