---
- name: Installation of curl
  ignore_errors: yes
  apt:
      pkg: curl
      state: present
      update_cache: true

- name: Check if Netdata is installed
  stat:
      path: /etc/netdata
  register: netdata

- name: Executing kickstart.sh (Netdata installation script)
  command: bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait
  args:
      chdir: /home/arsciand/
  ignore_errors: yes
  register: output
  when: netdata.stat.exists == false

- debug:
      var: output
  when: netdata.stat.exists == false

- name: Modifying /etc/netdata/netdata.conf memory usage
  replace:
      path: /etc/netdata/netdata.conf
      regexp: '# history = 3996'
      replace: 'history = 3600'
      backup: yes
  notify:
        - Restart Netdata

- name: Adding optimisation of Netdata in /etc/rc.local
  copy:
      src: rc.local
      dest: /etc/
      owner: root
      group: root
      mode: a+x

