---
- name: Checks Postfix installation
  stat:
      path: /etc/postfix
  register: postfix

- name: Initialises Postfix installation
  command: "{{ item }}"
  with_items:
      - debconf-set-selections <<< "postfix postfix/main_mailer_type string 'No Configuration'"
      - debconf-set-selections <<< "postfix postfix/mailname string rs1"
  when: postfix.stat.exists == false
  register: postfix_installed

- name: Installs Postfix
  apt:
      pkg: postfix
      state: present
      update_cache: yes

- name: Installs Mailutils
  apt:
      pkg: mailutils
      state: present
      update_cache: yes

- name: Configures /etc/postfix/main.cf
  copy:
      src: main.cf
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      backup: yes

- name: Adds virtual aliases
  copy:
      src: virtual
      dest: /etc/postfix/
      owner: root
      group: root
      backup: yes

- name: Generates DB and Maildir
  command: "{{ item }}"
  with_items:
      - postmap /etc/postfix/virtual
      - echo 'export MAIL=~/Maildir' | sudo tee -a /etc/bash.bashrc | sudo tee -a /etc/profile.d/mail.sh
  when: postfix_installed.changed
  notify:
      - Restarts Postfix
