---
- name: Creates update_script.sh & notif_script.sh for crontab in /home/arsciand
  copy:
      src: "{{ item }}"
      dest: /home/arsciand
      owner: arsciand
      group: arsciand
      mode: a+x
      backup: yes
  with_items:
      - update_script.sh
      - notif_script.sh
  register: cron

- name: Creates an entry "0 4 * * 1 /home/arsciand/update_script.sh" for cron
  cron:
      name: "update_script.sh 0 4 * * 1"
      weekday: 1
      hour: 4
      minute: 0
      user: root
      job: "/home/arsciand/update_script.sh"

- name: Creates an entry "@reboot /home/arsciand/update_script.sh" for cron
  cron:
      name: "update_script.sh @reboot"
      special_time: reboot
      user: root
      job: "/home/arsciand/update_script.sh"

- name: Creates an entry "0 0 * * * /home/arsciand/notif_script.sh" for cron
  cron:
      name: "notfi_script.sh 0 0 * * *"
      hour: 0
      minute: 0
      user: root
      job: "/home/arsciand/notif_script.sh"



