---
- name: Creating update_script.sh & notif_script.sh for crontab in /home/arsciand
  copy:
      src: "{{ item }}"
      dest: /home/arsciand
      owner: arsciand
      group: arsciand
      mode: a+x
      backup: yes
  with_items:
      - update_script.sh
      - notif_script.sh

- name: Updating crontab for root in /var/spool/cron/crontabs/root
  lineinfile:
      dest: /var/spool/cron/crontabs/root
      line: "{{ item }}"
  with_items:
      - '0 4 * * 1 /home/arsciand/update_script.sh'
      - '@reboot /home/arsciand/update_script.sh'
      - '0 0 * * * /home/arsciand/notif_script.sh'
