---
- name: Creating update_script.sh & notif_script.sh for crontab in /home/arsciand
  copy:
      src: "{{ item }}"
      dest: /home/arsciand
      owner: arsciand
      group: arsciand
      mode: a+x
      backup: yes
  with_items:
      - update_script.sh
      - notif_script.sh
  register: cron

- name: Creating root file in /var/spool/cron/crontabs/root
  file:
      path: /var/spool/cron/crontabs/root
      state: touch
      owner: root
      group: root
  when: cron.changed

- name: Updating crontab for root in /var/spool/cron/crontabs/root
  lineinfile:
      dest: /var/spool/cron/crontabs/root
      line: "{{ item }}"
  with_items:
      - '0 4 * * 1 (bash /home/arsciand/update_script.sh)'
      - '@reboot (bash /home/arsciand/update_script.sh)'
      - '0 0 * * * (bash /home/arsciand/notif_script.sh)'
