---
- name: Installation of OpenSSH Server
  apt:
      pkg: openssh-server
      state: present
      update_cache : true

- name: Starting OpenSSH Server
  server:
        name: ssh
        enabled: yes
        state: started

- name: Creation of .ssh
  file:
      path: ~/.ssh
      state: directory
      owner: arsciand
      group: arsciand

- name: Seting up authorized_keys file with rs1-key.pub
  copy:
      src: authorized_keys
      dest: ~/.ssh/
      owner: arsciand
      group: arsciand

- name: Modify /etc/ssh/sshd_config
  replace:
      path: "/etc/ssh/sshd_config"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
  with_items:
      - {regexp: '#Port 22', replace: 'Port 2222'}
      - {regexp: '#PermitRootLogin prohibit-password', replace: 'PermitRootLogin no'}
      - {regexp: '#PasswordAuthentication yes', replace: 'PasswordAuthentication no'}
  notify:
      - Restarted OpenSSH Server

