---
- name: Installation of OpenSSH Server
  apt:
      pkg: openssh-server
      state: installed
      update_cache : true
  notify:
      - Start OpenSSH Server

- name: Modify /etc/ssh/sshd_config
  replace:
      path: "/etc/ssh/sshd_config"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
  with_items:
      - { regexp: '#Port 22', replace: 'Port 2222'}
      - { regexp: '#PermitRootLogin prohibit-password', replace: 'PermitRootLogin no'}
      - { regexp: '#PasswordAuthentication yes', replace: 'PasswordAuthentication no'}
  notify:
      - Restart OpenSSH Server

