---
- name: Installation of Fail2Ban
  apt:
      pkg: fail2ban
      state: present
      update_cache: yes

- name: Adding jail.local in /etc/fail2ban/
  copy:
      src: jail.local
      path: /etc/fail2ban
      owner: root
      group: root
      backup: yes

- name: Adding nginx-dos.conf & portscan.conf in /etc/fail2ban/filter.d
  copy:
      src: "{{ item }}"
      path: /etc/fail2ban
      owner: root
      group: root
      backup: yes
  with_items:
      - nginx-dos.conf
      - portscan.conf
  - notify:
      - Restart Fail2Ban

