---
- name: Installs Fail2Ban
  apt:
      pkg: fail2ban
      state: present
      update_cache: yes

- name: Adds jail.local in /etc/fail2ban/
  copy:
      src: jail.local
      dest: /etc/fail2ban
      owner: root
      group: root
      backup: yes

- name: Adds nginx-dos.conf & portscan.conf in /etc/fail2ban/filter.d
  copy:
      src: "{{ item }}"
      dest: /etc/fail2ban/filter.d
      owner: root
      group: root
      backup: yes
  with_items:
      - nginx-dos.conf
      - portscan.conf
  notify:
      - Restarts Fail2Ban

