---
- name: Replace 01-netcfg.yaml for Static IP setup
  copy:
      src: 01-netcfg.yaml
      dest: /etc/netplan/
      owner: root
      group: root
      backup: yes
  register: netplan

- name: Apply Netplan
  command: netplan apply
  when: netplan.changed
