---
- name: Installation of Nginx
  apt:
      pkg: nginx
      state: present
      update_cache: yes

- name: Adjusting /etc/nginx/nginx.conf for security improvement
  replace:
      path: /etc/nginx/nginx.conf
      regexp: '^#(.*# server_tokens off;.*)'
      replace: '\1'
      backup: yes

- name: Adding DOS conf for Netdata in /etc/nginx/conf
  lineinfile:
      path: /etc/nginx/nginx.conf
      line: limit_req_zone $binary_remote_addr zone=one:1m rate=20r/s;
      insertafter: default_type*
      backup: yes
